### ISSUE TITLE
script usage to exclude some command from scriptreplay

### ISSUE THREAD

**Issue by pooja-choudhari** [scoopex/scriptreplay_ng#9]
Hello, Is there a way to exclude some commands such as vi/cat/less/more from being replayed with the scriptreplay originally captured with script. visual editing commands cause a lot of noise which I would like to reduce if possible using a combination or script/scriptreplay maybe depending on bytes from the timing file or even better from the command to replay.

Let me know if this is possible.

**Comment by scoopex** [comment]
Currently not :-) But if you are perl hacker, it might be possible that you can implement that :-)
